version: "3.9"

services:
    api:
        build:
            context: .
            dockerfile: ./docker/local/django/Dockerfile
        command: /start
        volumes:
            - .:/app
            - static_volume:/app/staticfiles
            - media_volume:/app/mediafiles
        ports:
            - "8000"
        env_file:
            - .env
        depends_on:
            - postgres-db
        networks:
            - estate-react

    postgres-db:
        image: postgres:14.3-alpine
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=${DATABASE_USER}
            - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
            - POSTGRES_DB=${DATABASE_NAME}
        networks:
            - estate-react
networks:
   estate-react:
       driver: bridge

volumes:
    postgres_data:
    static_volume:
    media_volume:
